# Python Practice 

In [4]:
#Prime number
x= int(input("Enter a number: "))
temp = 0
for i in range(2,x):
    if (x% i == 0):
        print("The entered integer is NOT a  PRIME!")
        temp+= 1 
        break
if (temp==0):
    print("The entered integer is NOT a  PRIME!")

Enter a number: 5
The entered integer is NOT a  PRIME!


In [5]:
#Palindrome String
string = input("Enter a number: ")
lst= ''
for i in range(1, len(string)+1):
    lst += string [-1]
if (lst == string):
    print("The entered integer is a Palindrome!")
else:
    print("The entered integer is NOT a  Palindrome!")


Enter a number: 6
The entered integer is a Palindrome!


In [6]:
#Pyramid sequence
n = int(input("Enter an integer: "))
for i in range(1, n+1):
    for k in range(n, i, -1):
        print ("", end = ' ')
    for j in range(1, i+1):
        print(i, end = '')
    print ()


Enter an integer: 7
      1
     22
    333
   4444
  55555
 666666
7777777


In [7]:
#Fibonacci series
n= int(input("Enter a value to generate Fibonacci sequence: ") )
lst= [0,1]
for i in range (n-2):
    lst.append(lst[-1] + lst [-2])
print (lst)


Enter a value to generate Fibonacci sequence: 8
[0, 1, 1, 2, 3, 5, 8, 13]


In [9]:
import numpy as np
lst= [1,2,3,4,5]
A = np.array([1,2,3,4,5])
np.arange(0,10,2)
np.arange(2,30,5)
A.shape
A.reshape(1,5)
B = [1,2,3,4,5,6,7,8,9]
B = np.array([1,2,3,4,5,6,7,8,9])
B.reshape(3,3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
Z=np.zeros((4,3))
Z
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
#dot product of 2 matrices
I = np.eye(3)
I
D= np. arange(1,10).reshape(3,3)
D
M= np.dot(D, I)


In [12]:
#add elements
np.sum(M)
#add along the rows
np.sum(M, axis= 1)


array([ 6., 15., 24.])